[package]
name = "matcha_core"
version = "0.1.0"
edition = "2021"

[dependencies]
jpreprocess = { version = "0.10.0", features = ["naist-jdic"] }
once_cell = "1.20.2"
serde_json = "1.0.128"
thiserror = "1.0.64"
